robot_controller:
  ros__parameters:
    relay_control:
      relay_pins: [5, 6]
    relay_states: [true, false] 
    camera:
      topic: "/camera/image_raw"
      resolution: [640, 480]
      framerate: 30
    motors:
      motor_0:
        id: 0
        speed: 0.5
        angle: 45.0
      motor_1:
        id: 1
        speed: 0.3
        angle: 90.0
      motor_2:
        id: 2
        speed: 0.8
        angle: 30.0
